class Exception {
  public function Exception(message)
  {
    print("To verify Exception contructor happens");
    self.message = message;
  }
}

class IndexOutOfBoundsException : Exception {
  public function IndexOutOfBoundsException(message)
  {
    // the base is not called automatically, because it doesn't have 0
    // arguments
    // therefore we must call it directly
    base(message); 
  }
}

try {
  throw IndexOutOfBoundsException(-1);
}
catch(e)
{
  print(e);
  // This fails, since instance types for IIN does not look at it's parents
  // TODO
  if('message' in e)
  {
    print(e.message);
  }

  print(e);
}








