class Init 
{
  public function Init()
  {
    try 
    {   
      0/0;
    }
    catch(e)
    { 
      try {
        print(e.message);
      }
      catch(e)
      {
        print("Hello World"); 
      }
    }
  }
}

try  {
  Init();
}
catch(e)
{
  print("Caught exception from Init()");
  print("    " + e);
  print("Done printing exception");
}


print("    calling Init again without a try catch block");
Init();


print("    [NOT REACHED] Trying again");
Init();
